[theme]
base="dark"
primaryColor="#1e6ed7"
backgroundColor="#1e6ed7"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"
showSidebarNavigation = false
disableWidgetStateDuplicationWarning = false
